<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>SimpleLog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.date.message.simplelog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.time.message.simplelog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.timezone.message.simplelog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.message.simplelog</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.message.simplelog</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.message.simplelog</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.control.message.simplelog</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>invalid.message.simplelog</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>support.type.scope.message.simplelog</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>message.simplelog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d\d/\d\d/\d\d)\s+(\d\d:\d\d:\d\d)\s+(\+\d\d\d\d)\s+((TRACE)|(DEBUG)|(INFO)|(WARN|ERROR)|(FATAL))\s+(([^/>]+(/[^/>]+)*)?>)\s+(.*)$</string>
			<key>name</key>
			<string>message.simplelog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.simplelog</string>
	<key>uuid</key>
	<string>3e8fdbc0-0e3f-11e2-892e-0800200c9a66</string>
</dict>
</plist>
